M48
; DRILL file {KiCad 8.0.6} date 2024-11-20T18:33:51-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-11-20T18:33:51-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0197
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0295
%
G90
G05
T1
X3.0315Y-3.2598
T2
X2.7815Y-3.1781
X2.7815Y-3.2864
M30
