M48
; DRILL file {KiCad 8.0.6} date 2024-11-22T17:50:04-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-11-22T17:50:04-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.750
%
G90
G05
T1
X77.0Y-82.8
T2
X70.65Y-80.725
X70.65Y-83.475
M30
